#include "\A3_Aegis\basicDefines_A3.hpp"
#include "cfgPatches.hpp"
#include "cfgSounds.hpp"
#include "cfgSoundShaders.hpp"
#include "cfgSoundSets.hpp"
#include "cfgAmmo.hpp"
#include "cfgVehicles.hpp"
class Mode_SemiAuto;
class Mode_Burst;
class Mode_FullAuto;
#include "cfgWeapons.hpp"