DEPRECATED_CLASS(I_P_Offroad_01_comms_F,Police_I_P_Offroad_01_comms_F);
DEPRECATED_CLASS(I_P_Offroad_01_covered_F,Police_I_P_Offroad_01_covered_F);
DEPRECATED_CLASS(I_P_Offroad_01_police_F,Police_I_P_Offroad_01_police_F);