class CfgVehicles
{
    /* Holders inheritance and definitions */
	#include "P:\A3_Aegis\itemHolders.hpp"

	WEAPON_HOLDER(arifle_SCAR_F,20Rnd_762x51_Mag,$STR_A3_A_CfgWeapons_arifle_SCAR_F0,EdSubcat_AssaultRifles)
	WEAPON_HOLDER(arifle_SCAR_GL_F,20Rnd_762x51_Mag,$STR_A3_A_CfgWeapons_arifle_SCAR_GL_F0,EdSubcat_AssaultRifles)
	WEAPON_HOLDER(arifle_SCAR_short_F,20Rnd_762x51_Mag,$STR_A3_A_CfgWeapons_arifle_SCAR_short_F0,EdSubcat_AssaultRifles)
	WEAPON_HOLDER(arifle_SCAR_grip_F,20Rnd_762x51_Mag,$STR_A3_A_CfgWeapons_arifle_SCAR_grip_F0,EdSubcat_AssaultRifles)
	WEAPON_HOLDER(arifle_SCAR_black_F,20Rnd_762x51_Mag,$STR_A3_A_CfgWeapons_arifle_SCAR_black_F0,EdSubcat_AssaultRifles)
	WEAPON_HOLDER(arifle_SCAR_GL_black_F,20Rnd_762x51_Mag,$STR_A3_A_CfgWeapons_arifle_SCAR_GL_black_F0,EdSubcat_AssaultRifles)
	WEAPON_HOLDER(arifle_SCAR_short_black_F,20Rnd_762x51_Mag,$STR_A3_A_CfgWeapons_arifle_SCAR_short_black_F0,EdSubcat_AssaultRifles)
	WEAPON_HOLDER(arifle_SCAR_grip_black_F,20Rnd_762x51_Mag,$STR_A3_A_CfgWeapons_arifle_SCAR_grip_black_F0,EdSubcat_AssaultRifles)
	WEAPON_HOLDER(arifle_SCAR_khaki_F,20Rnd_762x51_Mag,$STR_A3_A_CfgWeapons_arifle_SCAR_khaki_F0,EdSubcat_AssaultRifles)
	WEAPON_HOLDER(arifle_SCAR_GL_khaki_F,20Rnd_762x51_Mag,$STR_A3_A_CfgWeapons_arifle_SCAR_GL_khaki_F0,EdSubcat_AssaultRifles)
	WEAPON_HOLDER(arifle_SCAR_short_khaki_F,20Rnd_762x51_Mag,$STR_A3_A_CfgWeapons_arifle_SCAR_short_khaki_F0,EdSubcat_AssaultRifles)
	WEAPON_HOLDER(arifle_SCAR_grip_khaki_F,20Rnd_762x51_Mag,$STR_A3_A_CfgWeapons_arifle_SCAR_grip_khaki_F0,EdSubcat_AssaultRifles)
};