DEPRECATED_CLASS(I_P_PoliceOfficer_F,Police_I_P_PoliceOfficer_F);
DEPRECATED_CLASS(I_P_PoliceOfficer_Rifle_F,Police_I_P_PoliceOfficer_Rifle_F);
DEPRECATED_CLASS(I_P_PoliceOfficer_SG_F,Police_I_P_PoliceOfficer_SG_F);
DEPRECATED_CLASS(I_P_TacPoliceOfficer_F,Police_I_P_TacPoliceOfficer_F);
DEPRECATED_CLASS(I_P_TacPoliceOfficer_Sniper_F,Police_I_P_TacPoliceOfficer_Sniper_F);
DEPRECATED_CLASS(I_P_TacPoliceOfficer_SG_F,Police_I_P_TacPoliceOfficer_SG_F);
DEPRECATED_CLASS(I_P_TacPoliceOfficer_UGV_02_F,Police_I_P_TacPoliceOfficer_UGV_02_F);
DEPRECATED_CLASS(I_P_Helipilot_F,Police_I_P_Helipilot_F);