DEPRECATED_CLASS(O_T_Heli_Attack_02_dynamicLoadout_F,Aegis_O_T_Heli_Attack_02_dynamicLoadout_F)
DEPRECATED_CLASS(O_A_Heli_Attack_02_dynamicLoadout_F,Aegis_O_A_Heli_Attack_02_dynamicLoadout_F)
DEPRECATED_CLASS(O_R_Heli_Attack_02_dynamicLoadout_ard_F,Aegis_O_R_Heli_Attack_02_dynamicLoadout_ard_F)
DEPRECATED_CLASS(O_R_Heli_Attack_02_dynamicLoadout_F,Aegis_O_R_Heli_Attack_02_dynamicLoadout_F)