#DEFINE TEAST 0
#DEFINE TWEST 1
#DEFINE TGUERRILA 2
#DEFINE TCIVILIAN 3
#DEFINE TSIDEUNKNOWN 4
#DEFINE TENEMY 5
#DEFINE TFRIENDLY 6
#DEFINE TLOGIC 7

#DEFINE TRUE 1
#DEFINE FALSE 0

#DEFINE VSOFT 0
#DEFINE VARMOR 1
#DEFINE VAIR 2

// TYPE SCOPE
#DEFINE PRIVATE 0
#DEFINE PROTECTED 1
#DEFINE PUBLIC 2

#DEFINE CANSEERADAR 1
#DEFINE CANSEEEYE 2
#DEFINE CANSEEOPTICS 4
#DEFINE CANSEEEAR 8
#DEFINE CANSEECOMPASS 16
#DEFINE CANSEERADARC CANSEERADAR+CANSEECOMPASS
#DEFINE CANSEEALL 31

#DEFINE READANDWRITE 0 //! ANY MODIFICATIONS ENABLED
#DEFINE READANDCREATE 1 //! ONLY ADDING NEW CLASS MEMBERS IS ALLOWED
#DEFINE READONLY 2 //! NO MODIFICATIONS ENABLED
#DEFINE READONLYVERIFIED 3 //! NO MODIFICATIONS ENABLED, CRC TEST APPLIED

#DEFINE LOCKNO		0
#DEFINE LOCKCADET	1
#DEFINE LOCKYES		2

#DEFINE WEAPONNOSLOT		0	// DUMMY WEAPONS
#DEFINE WEAPONSLOTPRIMARY	1	// PRIMARY WEAPONS
#DEFINE WEAPONSLOTSECONDARY	4	// SECONDARY WEAPONS
#DEFINE WEAPONSLOTHANDGUN	2	// HANDGUN
#DEFINE WEAPONSLOTHANDGUNITEM	16 // HANDGUN MAGAZINES
#DEFINE WEAPONSLOTITEM		256	// ITEMS
#DEFINE WEAPONSLOTBINOCULAR	4096	// BINOCULAR
#DEFINE WEAPONHARDMOUNTED	65536

#DEFINE SPEED_STATIC 1E10

#DEFINE NEVER_DESTROY 1000	// FOR MP - DESTROYING DEAD BODIES

#DEFINE TRACERECOLOR 0.2,0.8,0.1
#DEFINE TRACERWCOLOR 0.8,0.5,0.1
#DEFINE TRACERGCOLOR 0.7,0.7,0.5
#DEFINE TRACERNCOLOR 0,0,0 // USED FOR SNIPER / SILENCED RIFLES

#DEFINE TRACERECOLORF {TRACERECOLOR,0.040}
#DEFINE TRACERWCOLORF {TRACERWCOLOR,0.040}
#DEFINE TRACERGCOLORF {TRACERGCOLOR,0.040}
#DEFINE TRACERNCOLORF {TRACERNCOLOR,0.005}

#DEFINE TRACERSECOLORF {TRACERECOLOR,0.25}
#DEFINE TRACERSWCOLORF {TRACERWCOLOR,0.25}

#DEFINE TRACER_W_ALWAYS TRACERCOLOR[]=TRACERWCOLORF;TRACERCOLORR[]=TRACERWCOLORF
#DEFINE TRACER_W_OPTIONAL TRACERCOLOR[]=TRACERWCOLORF;TRACERCOLORR[]=TRACERNCOLORF
#DEFINE TRACER_W_STRONG TRACERCOLOR[]=TRACERSWCOLORF;TRACERCOLORR[]=TRACERSWCOLORF

#DEFINE TRACER_E_ALWAYS TRACERCOLOR[]=TRACERECOLORF;TRACERCOLORR[]=TRACERECOLORF
#DEFINE TRACER_E_OPTIONAL TRACERCOLOR[]=TRACERECOLORF;TRACERCOLORR[]=TRACERNCOLORF
#DEFINE TRACER_E_STRONG TRACERCOLOR[]=TRACERSECOLORF;TRACERCOLORR[]=TRACERSECOLORF

#DEFINE TRACER_G_ALWAYS TRACERCOLOR[]=TRACERGCOLORF;TRACERCOLORR[]=TRACERGCOLORF
#DEFINE TRACER_G_OPTIONAL TRACERCOLOR[]=TRACERGCOLORF;TRACERCOLORR[]=TRACERNCOLORF

#DEFINE TRACER_N_ALWAYS TRACERCOLOR[]=TRACERNCOLORF;TRACERCOLORR[]=TRACERNCOLORF

#DEFINE LOCKNO		0
#DEFINE LOCKCADET	1
#DEFINE LOCKYES		2

enum VehicleCompartments
{
  Compartment1 = 1,
  Compartment2 = 2,
  Compartment3 = 4,
  Compartment4 = 8
  // up to Compartment32 = 0x80000000
};

//enum {StabilizedInAxesNone,StabilizedInAxisX,StabilizedInAxisY,StabilizedInAxesBoth}


#DEFINE CM_NONE        0
#DEFINE CM_LOCK_VISUAL 1
#DEFINE CM_LOCK_IR     2
#DEFINE CM_LOCK_LASER  4
#DEFINE CM_LOCK_RADAR  8
#DEFINE CM_MISSILE     16