DEPRECATED_CLASS(U_B_MCU_desert_F,Marine_U_B_MCU_desert_F);
DEPRECATED_CLASS(U_B_MCU_wdl_F,Marine_U_B_MCU_wdl_F);
DEPRECATED_CLASS(U_B_MCU_tshirt_desert_F,Marine_U_B_MCU_tshirt_desert_F);
DEPRECATED_CLASS(U_B_MCU_tshirt_wdl_F,Marine_U_B_MCU_tshirt_wdl_F);
DEPRECATED_CLASS(U_B_MCU_vest_desert_F,Marine_U_B_MCU_vest_desert_F);
DEPRECATED_CLASS(U_B_MCU_vest_wdl_F,Marine_U_B_MCU_vest_wdl_F);